### ISSUE TITLE
Cross Faction Flight Paths

### ISSUE THREAD

**Issue by impstrmtrpr007** [gitdalisar/mod-Faction-Free#1]
While I am able to talk to the flight masters at each of the Alliance/Horde areas I am not able to access the flight path for the cross faction. Example: For some of the flight masters, not in the main cities, I am able to fly to any of the Horde locations that I have open but not any of the Alliance based ones. In the main cities (e.g. Stormwind, Iron Forge, etc.) I get the message "You don't know any flight paths connected to this one". For reference I have a Horde Tauren that I went into both Stormwind and Iron Forge to test the paths and talked to Alliance flight masters along the route.

**Comment by gitdalisar** [comment]
Thanks for the request!
Looks like I will need to add new flight paths within the TaxiPath.DBC file. So once I get that done, I'll also need to roll that into the MPQ I have. Shouldn't need any SQL changes from what I am seeing. I'll work on it some this weekend to see if I'm right and if so I'll update here to let you know if my hypothesis is correct and how long the ETA would be. Thanks again!

**Comment by gitdalisar** [comment]
Looks like it may be a bit more compliacted. I'm not adding any new taxi nodes so don't need to touch the TaxiNode file. I did make the path between horde and alliance cities in TaxiPath and patch that in, saw it, could select it, but as soon as I tried to use it the server bounced. So I went and looked into the TaxiPathNode file, added routes for my new path, but that shot me out into the nether way off the map and killed me once I used it. It could have been a typo on my xyz coords but will need to research it a bit more. No ETA on it, but I'll be looking into it before working on other things to try and get this cleaned up if possible.

**Comment by gitdalisar** [comment]
This may be a bit more complicated as it appears one of the attributes we need to use, the taximask for characters, appears to be factional, so we may not have an easy way for this. Logging this as reference: https://github.com/azerothcore/azerothcore-wotlk/issues/15163

**Comment by gitdalisar** [comment]
Have the LUA scripts made for character conversation, NPC made, gobjects placed for asthetics in major cities, and am validating the locations. Will teleport to start of dungeons/raids and capital cities. Will need to have LUA support for this portion of the mod. Will update documentation once this is patched into the repo.

**Comment by gitdalisar** [comment]
Implemented with LUA scripts and updating the FactionFree.sql file. I have also included a new sql file named EntryChecker.sql that you can run to validate if any entry, id, or GUID are already in use prior to importing the FactionFree.sql. If anything DOES come back from that checker, then you WILL need to update the FactionFree.sql script to values not in use in your specific environment.
