### ISSUE TITLE
[BUG] Unattackable Quest NPCs for Battered Hilt chain

### ISSUE THREAD

**Issue by Ghostsupthere** [gitdalisar/mod-Faction-Free#14]
I believe we found two NPCs that will need faction fixed. They are faction specific to their respective quest, they may need moved to a neutral attackable one.  These ones are *not* attackable and should be, they need killed and looted for a specific quest (Battered Hilt chain):

Horde Quest:
https://www.wowhead.com/wotlk/quest=24557/the-silver-covenants-scheme

Alliance Quest:
https://www.wowhead.com/wotlk/quest=14457/the-sunreaver-plan

NPCs are:
-36776 (Horde NPC killed by alliance)
-36774 (Alliance NPC killed by Horde)

Factions appear to be ID of 2027 (NPC 36774) and 2123 (NPC 36776) which is Silver Covenant and Sunreavers accordingly.

I am assuming these would need changed to an attackable neutral faction since those are likely too related to other quest givers.

See attached for full NPC info.

![AllianceNPC](https://github.com/gitdalisar/mod-Faction-Free/assets/124380903/8dca68bc-0074-47b8-85fe-d400898decf8)
![HordeNPC](https://github.com/gitdalisar/mod-Faction-Free/assets/124380903/0787c0fd-38d7-4825-ab6f-a5751f81a74a)

**Comment by gitdalisar** [comment]
Ahh yeah you are right.... since the Silver Covenant and Sunreavers would be opposing they would have been caught up in the allowing you to do quests for both. I probably just need to fix these two singular NPC... Let me see if I can find a faction that make sense for them. Thanks for bringing this up!

**Comment by gitdalisar** [comment]
Believe we can just set these two corresponding NPC to faction 7 (creature) which should make them targetable and attackable with no faction repercussions and also not make them aggro on sight. Code has been delivered for testing, will roll this into patch if successful. Will likely find more of these throughout the world, so if this works, will use this as the means of resolution moving forward.

**Comment by Ghostsupthere** [comment]
I can confirm the changes you sent resolved the issue. The quest was completed and the NPCs are attackable now.

Thanks!

**Comment by gitdalisar** [comment]
Patched in for version 1.3.1 so closing out BUG
