### ISSUE TITLE
[BUG] Player Hunter Pets attacking PVP flagged opposing faction

### ISSUE THREAD

**Issue by Ghostsupthere** [gitdalisar/mod-Faction-Free#15]
Player hunter pets are attacking opposing faction players if the player gets PVP flagged and the pet is on aggressive.

Ex:

Player A is alliance warrior
Player H is horde hunter

Player A becomes PVP flagged from various means, Player H cannot attack the player manually. If Player H has his pet on aggressive, Player A will be attacked if in range.

I'm not sure .npc info of the pet is any use here, because we tested multiple pets (different factions\ids each time) and different characters. Let me know if you want other information \ what I can gather that could help narrow it down.

![image](https://github.com/gitdalisar/mod-Faction-Free/assets/124380903/9578874e-9eeb-4e11-b356-38d1bc323b89)

**Comment by gitdalisar** [comment]
Interesting... I hadn't considered the pet would have a faction... that's really cool!  Nice find!

I'll do some research on this and see how I can resolve it for you!

**Comment by gitdalisar** [comment]
Found faction for pet is defined on line 270 of Pet.cpp so may can hard set that to something factionless. Pinged reporter for info on what actions resulted in PVP Flagging to ensure flagging was not in error.

**Comment by Ghostsupthere** [comment]
Unable to confirm cause of PVP flagging still. I have recompiled using the newest .CPP file (to confirm its not the town/city flag) and it still occurs randomly.

Latest occurrence was after a dungeon, some players spawned into town flagged, while others in the same group were not. 1 horde character and 1 alliance character was flagged while another was not. All players spawned into Stormwind after dungeon completion. (Honestly forget the dungeon, didn't note it at the time.)

Will need more testing to report more instance of it.

**Comment by gitdalisar** [comment]
Closing as could not replicate. Can reopen if issue persists.
