### ISSUE TITLE
[BUG] ToGC items are faction specific

### ISSUE THREAD

**Issue by Ghostsupthere** [gitdalisar/mod-Faction-Free#16]
Trial of the Crusader's items appear to be faction specific still.

Example item: 47808
--Item is a alliance specific mace, unable to be equipped by Horde

-Steps to replicate:
--Create horde level 80
--.additem 47808
--Attempt to equip

Error received is: "You can never use that item"

When the item drops in a raid, the faction that *cannot* equip the item will not see the loot roll chance either. The items dropping (alliance \ horde) appear to depend on who starts the fight via the NPC in the arena, this may aid in testing.

I believe there may be a faction flag in the items_template database preventing it?

Please let me know if I can post more \ help research.

**Comment by gitdalisar** [comment]
Found issue with the ExtraFlags attribute in item_template table. Issue should now be resolved and is patched in with 1.3.2 changes so closing out BUG.
