### ISSUE TITLE
[BUG] High Overlord Saurfang attacking Alliance characters in ICC entrance

### ISSUE THREAD

**Issue by Ghostsupthere** [gitdalisar/mod-Faction-Free#17]
High Overlord Saurfang is attacking alliance characters when entering the ICC raid:

https://www.wowhead.com/wotlk/npc=37187/high-overlord-saurfang

The later versions of him in the raid are not hostile \ attack, it is only this specific instance at the entrance:

![Saurfang attacking alliance entering ICC](https://github.com/gitdalisar/mod-Faction-Free/assets/124380903/eb38f877-de1d-425f-8ec4-3e4a97d12077)

**Comment by gitdalisar** [comment]
Are you running the latest .sql patch? I should have all 1735 factions moved away from that. Checking my database for "SELECT * FROM creature_template WHERE faction = 1735;" returns no rows. Doublecheck that you have that applied. If you still have the issue though let me know!

**Comment by gitdalisar** [comment]
Believe this to be resolved, couldn't recreate and no comments thereater.
