### ISSUE TITLE
[FEATURE] Convert `PlayerUpdates.cpp` to a diff/patch.

### ISSUE THREAD

**Issue by heyitsbench** [gitdalisar/mod-Faction-Free#20]
I would suggest that the `PlayerUpdates.cpp` file be converted to a diff or a patch file.
This solution is in use with my module, [mod-worgoblin](https://github.com/heyitsbench/mod-worgoblin), and it both allows for Github workflows to be used with the repository as well as better survival with updates made upstream with AzerothCore. As well, it can also help people look for changes they would need to make if they were to apply the changes to a private fork that has already been modified.

**Comment by gitdalisar** [comment]
@heyitsbench Yep working on that now. Appologies for not getting to this sooner. Rebuilding my env to the lastest branch and will have the new files for Player.cpp and PlayerUpdates.cpp here today.

**Comment by gitdalisar** [comment]
@heyitsbench the .cpp file has been updated and should work now. Please let me know if you continue to have any issues.
