### ISSUE TITLE
Problem with PlayerUpdates.cpp

### ISSUE THREAD

**Issue by Daimando** [gitdalisar/mod-Faction-Free#21]
When I compiled with a new AzerothCore update, I get an error that said the following.

'AchievementMgr::UpdateTimedAchievement; cannot access private member declared in class 'AchievementMgr'

How do I fix this?

**Comment by gitdalisar** [comment]
@Daimando Sorry for the delay. I've been pulled away for personal reasons. The underlining code changed with Azerothcore. I am rebuilding my server to the latest release and will have the updated files here today for you.,

**Comment by gitdalisar** [comment]
@Daimando issues should be resolved with new .cpp file being uploaded. Please try again and if issue persists, let me know!
